config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home', to: 'home#index'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @notice= 'jopa'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Erudite
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/header'
    = render 'shared/notice'
    = yield

app/views/shared/_header.html.haml
%header.p-3.bg-dark.text-white.w-100
  .container
    .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
      %a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none{:href => "/"}
      %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        %li
          = link_to 'Home', home_path, class: 'nav-link px-2 text-secondary'
        %li
          %a.nav-link.px-2.text-white{:href => "#"} Games
        %li
          %a.nav-link.px-2.text-white{:href => "#"} Account
      .text-end
        -if user_signed_in?
          %span.me-4= "Hello, #{current_user.name}!"
          =link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-danger'
        -else
          =link_to 'Login', new_user_session_path, class: 'btn btn-outline-light me-2'
          =link_to 'Sign-up', new_user_registration_path, class: 'btn btn-warning'

app/views/shared/_notice.html.haml
.container
  .row.d-flex.justify-content-center
    - if !notice.nil?
      .alert.alert-success.w-50.text-center= notice
    - if !alert.nil?
      .alert.alert-danger.w-50.text-center= alert